name       : python-pep517
version    : 0.12.0
release    : 1
source     :
    - https://pypi.io/packages/source/p/pep517/pep517-0.12.0.tar.gz : 931378d93d11b298cf511dd634cf5ea4cb249a28ef84160b3247ee9afb4e8ab0
homepage   : https://github.com/pypa/pep517
license    : MIT
component  : programming.python
summary    : API to call PEP 517 hooks for building Python packages
description: |
    PEP 517 specifies a standard API for systems which build Python packages.
setup      : |
    %python3_setup
install    : |
    %python3_install
